import matplotlib.pyplot as plt
import numpy as np

sum = 0

a = 1
b = 2
c = a+b
count = 4000000
fin = [a,b,c]
while(c<count):
	if(c%2==0):
		sum += c
	a = b
	b = c
	c = a+b
	fin.append(c)


x = np.linspace(0, len(fin), 100)
y = np.exp(x/2)

plt.figure(1)
plt.plot(x, y)
plt.xlabel('$x$')
plt.ylabel('$\exp(x)$')

print fin

plt.plot(fin)
plt.show()
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''
